/**
 * AUTO-GENERATED from Book1.xlsx — do not edit by hand.
 * Re-run fix_column_headers.py to regenerate.
 */
export const COLUMN_HEADERS: Record<string, string> = {
  "A": "Timestamp",
  "B": "SURVEY DATE",
  "C": "SURVEYOR NAME",
  "D": "SURVEY LOCATION",
  "E": "BRAND & MODEL (Qualifying Question)",
  "F": "VIN No. (Qualifying Question)",
  "G": "Please take a picture of the VIN no. and upload it here. (Qualifying Question)",
  "H": "ODOMETER READING (Kms)",
  "I": "MODE OF PURCHASE",
  "J": "DATE OF PURCHASING THE VEHICLE FROM DEALER / PREVIOUS OWNER",
  "K": "USER NAME",
  "L": "USER AGE (YEARS) (enter only a full number between 18 to 60)",
  "M": "USER AGE GROUP",
  "N": "USER PROFESSION",
  "O": "MOBILE NUMBER",
  "P": "ALTERNATE MOBILE NUMBER",
  "Q": "OWNERSHIP (OWN / HIRED)",
  "R": "FOR WHAT PURPOSE DO YOU USE THE VEHICLE?",
  "S": "MODEL YEAR OF YOUR VEHICLE",
  "T": "HOW LONG HAVE YOU BEEN USING THIS VEHICLE?",
  "U": "PREVIOUS VEHICLE USED Brand & Model",
  "V": "HOW LONG DID YOU USE THE PREVIOUS VEHICLE? (Years)",
  "W": "1. Will you recommend your vehicle to your friends / relatives / family members?",
  "X": "2. On a scale of 0 to 10, how likely are you to recommend your vehicle to your friends and relatives? (9 & 10 means “Yes Always recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”)",
  "Y": "Q2-1. REASON FOR NOT RECOMMENDING [If answer to the above question Q4-1 is \"No\", select a rating from 0 (will not at all recommend) to 6 (recommend but with reservations)] below: [No]",
  "Z": "Q2-2. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"May be\", select a rating 7 (less likely) or 8 (more likely)] below: [May be]",
  "AA": "Q2-3. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"Yes\", select a rating 9 (Will recommend) or 10 (definitely/gladly recommend)] below: [Yes]",
  "AB": "3a)1 why will you recommend your vehicle?",
  "AC": "3a)2 why will you recommend your vehicle?",
  "AD": "3a)3 why will you recommend your vehicle?",
  "AE": "3a)4 why will you recommend your vehicle?",
  "AF": "3a)5 why will you recommend your vehicle?",
  "AG": "3b.1. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "AH": "3b. 2. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "AI": "3b. 3. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "AJ": "3b. 4. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "AK": "3b. 5. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "AL": "Upload complaint pictures",
  "AM": "Upload complaint pictures 1",
  "AN": "4)1 why will you not recommend your vehicle?",
  "AO": "4)2 why will you not recommend your vehicle?",
  "AP": "4)3 why will you not recommend your vehicle?",
  "AQ": "4)4 why will you not recommend your vehicle?",
  "AR": "4)5 why will you not recommend your vehicle?",
  "AS": "Upload complaint pictures_2",
  "AT": "Upload complaint pictures_3",
  "AU": "Brake",
  "AV": "Electrical",
  "AW": "Engine",
  "AX": "Load",
  "AY": "Maintenance",
  "AZ": "Mileage",
  "BA": "Mirror",
  "BB": "Vehicle",
  "BC": "Seat",
  "BD": "Sound",
  "BE": "Roof top (soft top)",
  "BF": "Spare parts",
  "BG": "Style",
  "BH": "Suspension",
  "BI": "Tyre",
  "BJ": "Vehicle price",
  "BK": "Income",
  "BL": "Windshield",
  "BM": "Brand image",
  "BN": "Q1-1 WHERE DO YOU GET YOUR VEHICLE SERVICED?",
  "BO": "Q1-2 Dealer / Authorized Workshop Name",
  "BP": "Q1-3 WHAT TIME FREQUENCY DO YOU GET YOUR VEHICLE SERVICED?",
  "BQ": "Q1-4 WHAT KMS FREQUENCY DO YOU GET YOUR VEHICLE SERVICED?",
  "BR": "A1. Will you recommend / tell / advise your friends or family members for servicing their vehicle at Authorized Service workshop / Authorized Dealer?",
  "BS": "A2. We have a rating scale from 0 to 10 to understand this better. (9 & 10 means “you will definitely recommend workshop / Dealers to service their vehicle”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choose any score between 0 and 10. So which score would you like to give?",
  "BT": "Q2-4. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"Yes\", select a rating from 9 (will recommend) to 10 (definitely/gladly recommend)] below: [Yes]",
  "BU": "Q2-3. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"May be\", select a rating from 7 (less likely recommend) to 8 (more likely recommend)] below: [May be]",
  "BV": "Q2-2. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"No\", select a rating from 0 (will not at all recommend) to 6 (recommend but with reservations)] below: [No]",
  "BW": "3a)1 Which experience you like the most to recommend Workshop / Dealer?",
  "BX": "3a)2 Which experience you like the most to recommend Workshop / Dealer?",
  "BY": "3a)3 Which experience you like the most to recommend Workshop / Dealer?",
  "BZ": "3b)1 Can you please tell us if there are any expectation or areas of improvement you wish to experience in your workshop visit for Service?",
  "CA": "3b)2 Can you please tell us if there are any expectation or areas of improvement you wish to experience in your workshop visit for Service?",
  "CB": "3b)3 Can you please tell us if there are any expectation or areas of improvement you wish to experience in your workshop visit for Service?",
  "CC": "4)1 What are the main reasons for you have not recommend Workshop / Dealer?",
  "CD": "4)2 What are the main reasons for you have not recommend Workshop / Dealer?",
  "CE": "4)3 What are the main reasons for you have not recommend Workshop / Dealer?",
  "CF": "a) Have you received Service reminder call",
  "CG": "b) Appointment given",
  "CH": "c) Vehicle test drive taken while making job cards to understand the complaints",
  "CI": "d) Customer lounge Facilities",
  "CJ": "e) Staff behaviour",
  "CK": "f) All complaints reported are resolved",
  "CL": "g) Fairness of charges",
  "CM": "h) Explanation of Work done",
  "CN": "i) Washing quality",
  "CO": "j) Test drive offered before billing",
  "CP": "A6. Are you satisfied with Vehicle Performance after service? (VPS)",
  "CQ": "A7. Currently are you facing any issues / complaints in vehicle? No of customer not satisfied with vehicle performance after service",
  "CR": "A8. Have you reported this issue to the Service advisor during Job card making during your last Visit?",
  "CS": "A9. Fixing problems First Time Right",
  "CT": "A10. Delivery as per promised time",
  "CU": "A11. Overall, how satisfied are you with your experience at our workshop/dealership for servicing your vehicle? (Please rate your satisfaction on a scale of “0 to 10”)",
  "CV": "A11. Overall, how satisfied are you with your experience at our workshop/dealership for servicing your vehicle? (Please rate your satisfaction on a scale of “0 to 10”)_2",
  "CW": "A11. Overall, how satisfied are you with your experience at our workshop/dealership for servicing your vehicle? (Please rate your satisfaction on a scale of “0 to 10”)_3",
  "CX": "A11. Overall, how satisfied are you with your experience at our workshop/dealership for servicing your vehicle? (Please rate your satisfaction on a scale of “0 to 10”)_4",
  "CY": "B1. Reason for not choosing the Authorized Service Centers?",
  "CZ": "B2. Reason for not choosing the Authorized Service Centers?",
  "DA": "B3. Reason for not choosing the Authorized Service Centers?",
  "DB": "B2. How would you rate the quality of Authorized service center? (Choose any score from 1 - 10, \"1 means worst, 10 means best\")",
  "DC": "B2. How would you rate the quality of Authorized service center? (Choose any score from 9,10 means best\") [Best]",
  "DD": "B2. How would you rate the quality of Authorized service center? (Choose any score from1 to 6 means Bad\") [Bad]",
  "DE": "B2. How would you rate the quality of Authorized service center? (Choose any score from 7,8 means average\") [Average]",
  "DF": "Complaint group (L2)",
  "DG": "Complaint group (L2)_2",
  "DH": "Complaint group (L2)_3",
  "DI": "Complaint group (L2)_4",
  "DJ": "Complaint group (L2)_5",
  "DK": "Complaint group (L2)_6",
  "DL": "Complaint group (L2)_7",
  "DM": "Complaint group (L2)_8",
  "DN": "Complaint group (L2)_9",
  "DO": "Complaint group (L2)_10",
  "DP": "Complaint group (L2)_11",
  "DQ": "Complaint group (L2)_12",
  "DR": "Complaint group (L2)_13",
  "DS": "Complaint group (L2)_14",
  "DT": "Complaint group (L2)_15",
  "DU": "Complaint group (L2)_16",
  "DV": "Complaint group (L2)_17",
  "DW": "Complaint group (L2)_18",
  "DX": "Complaint group (L2)_19",
  "DY": "Complaint group (L2)_20",
  "DZ": "Complaint group (L2)_21",
  "EA": "Complaint group (L2)_22",
  "EB": "Complaint group (L2)_23",
  "EC": "Complaint group (L2)_24",
  "ED": "Complaint group (L2)_25",
  "EE": "Complaint group (L2)_26",
  "EF": "Complaint group (L2)_27",
  "EG": "Complaint group (L2)_28",
  "EH": "Complaint group (L2)_29",
  "EI": "Complaint group (L2)_30",
  "EJ": "Complaint group (L2)_31",
  "EK": "Complaint group (L2)_32",
  "EL": "Complaint group (L2)_33",
  "EM": "Complaint group (L2)_34",
  "EN": "Which part not available?",
  "EO": "In which Location it is not available?",
  "EP": "Front brake noise",
  "EQ": "Front brake poor",
  "ER": "Front Brake tight",
  "ES": "Rear brake noise",
  "ET": "Rear brake poor",
  "EU": "Rear brake tight",
  "EV": "ABS Not working",
  "EW": "Hand brake poor",
  "EX": "Brake poor",
  "EY": "Clutch cable [less life]",
  "EZ": "Clutch cable [Cable breakage]",
  "FA": "Brake cable [less life]",
  "FB": "Brake cable [Cable breakage]",
  "FC": "Speedo cable [less life]",
  "FD": "Speedo cable [Cable breakage]",
  "FE": "Chain issues",
  "FF": "Chain case issues",
  "FG": "Clutch loose (Remarks)",
  "FH": "Clutch Noise",
  "FI": "Clutch hard",
  "FJ": "Clutch life is low [Clutch plate wear]",
  "FK": "Clutch life is low [Clutch plate burning]",
  "FL": "What is the issue in speedometer?",
  "FM": "TSL (Indicator) [Beeper Sound not coming]",
  "FN": "TSL (Indicator) [Light Not working]",
  "FO": "TSL (Indicator) [water entry]",
  "FP": "TSL (Indicator) [crack]",
  "FQ": "Head light [DC headlamp]",
  "FR": "Head light [LED headlamp]",
  "FS": "Tail lamp not working [Bulb]",
  "FT": "Tail lamp not working [LED]",
  "FU": "Horn issues",
  "FV": "Switch problem",
  "FW": "Locks not working [Ignition key not working]",
  "FX": "Locks not working [Side lock not working]",
  "FY": "Locks not working [Fuel tank cap lock not working]",
  "FZ": "Engine noise [Top side]",
  "GA": "Engine noise [Bottom side]",
  "GB": "Engine noise [Unknown]",
  "GC": "Engine oil leak",
  "GD": "Engine Heat [LH side]",
  "GE": "Engine Heat [RH side]",
  "GF": "Engine Heat [Both]",
  "GG": "Engine parts rust",
  "GH": "Gear noise Upshifitng",
  "GI": "Gear noise Downshifting",
  "GJ": "Gear noise Both",
  "GK": "Gear shifting hard Upshifitng",
  "GL": "Gear shifting hard Downshifting",
  "GM": "Gear shifting hard Both",
  "GN": "Not Coming to Neutral",
  "GO": "Additional gear required",
  "GP": "Handle bar noise [Cornering]",
  "GQ": "Handle bar noise [Pot holes]",
  "GR": "Handle bar noise [Bumpy roads]",
  "GS": "Handle bar noise [Others]",
  "GT": "Handle bar loose [Cornering]",
  "GU": "Handle bar loose [Pot holes]",
  "GV": "Handle bar loose [Bumpy roads]",
  "GW": "Handle bar loose [Others]",
  "GX": "Handle bar Tight [Cornering]",
  "GY": "Handle bar Tight [Pot holes]",
  "GZ": "Handle bar Tight [Bumpy roads]",
  "HA": "Handle bar Tight [Others]",
  "HB": "Handle bar jam [Cornering]",
  "HC": "Handle bar jam [Pot holes]",
  "HD": "Handle bar jam [Bumpy roads]",
  "HE": "Handle bar jam [Others]",
  "HF": "Handle bar jam [Cornering]_2",
  "HG": "Handle bar jam [Pot holes]_2",
  "HH": "Handle bar jam [Bumpy roads]_2",
  "HI": "Handle bar jam [Others]_2",
  "HJ": "handle bar bend [Yes-Is vehicle fall down?]",
  "HK": "handle bar bend [No-Is vehicle fall down?]",
  "HL": "Handle Bar shaking [<=25 kmph]",
  "HM": "Handle Bar shaking [25-50 kmph]",
  "HN": "Handle Bar shaking [>=50 kmph]",
  "HO": "Handle bar vibration [LH side]",
  "HP": "Handle bar vibration [RH side]",
  "HQ": "Handle bar vibration [Both side]",
  "HR": "Kicker issues",
  "HS": "If Kicker is hard",
  "HT": "Q-What mileage are you getting?",
  "HU": "Q-What is your average Speed using regularly?",
  "HV": "Q-What kind of traffic are you mostly using?",
  "HW": "Usually how many passenger will travel?",
  "HX": "Usually how much Load are you carry?",
  "HY": "Low Speed",
  "HZ": "What is the top speed are you Expecting?",
  "IA": "Muffler Noise [Rough road]",
  "IB": "Muffler Noise [plain road]",
  "IC": "Muffler smoke more [Idling speed]",
  "ID": "Muffler smoke more [While running]",
  "IE": "Muffler Rust-Where is the rust and specify the location?",
  "IF": "Self start problem - What is the issue? [Taking Many self for starting]",
  "IG": "Self start problem - What is the issue? [in gear condition]",
  "IH": "Self start problem - What is the issue? [Not at all starting]",
  "II": "Kick start problem - What is the issue?",
  "IJ": "Front suspension Noise Issue [Cornering]",
  "IK": "Front suspension Noise Issue [Pot holes]",
  "IL": "Front suspension Noise Issue [Bumpy roads]",
  "IM": "Front suspension Noise Issue [Normal road]",
  "IN": "Oil leak from front suspension",
  "IO": "Front suspension Hard - Usually how many passenger will travel?",
  "IP": "Front suspension Hard - Usually how much Load are you carry?",
  "IQ": "Front suspension Hard - How frequently you fill air in Tyre?",
  "IR": "Front suspension Soft - Usually how many passenger will travel?",
  "IS": "Front suspension Soft-Usually how much Load are you carry?",
  "IT": "Front suspension Soft - How frequently you fill air in Tyre?",
  "IU": "Rear suspension Hard - Usually how many passenger will travel?",
  "IV": "Rear suspension Hard - Usually how much Load are you carry?",
  "IW": "Rear suspension Hard-How frequently you fill air in Tyre?",
  "IX": "Rear suspension soft- Usually how many passenger will travel?",
  "IY": "Rear suspension soft - Usually how much Load are you carry?",
  "IZ": "Rear suspension soft -How frequently you fill air in Tyre?",
  "JA": "Rear suspension Noise - When it is happening? and at what speed? [Cornering]",
  "JB": "Rear suspension Noise - When it is happening? and at what speed? [Pot holes]",
  "JC": "Rear suspension Noise - When it is happening? and at what speed? [Bumpy roads]",
  "JD": "Rear suspension Noise - When it is happening? and at what speed? [Normal road]",
  "JE": "Front side noise - Can you specify the location? and at what speed? [Meter noise]",
  "JF": "Front side noise - Can you specify the location? and at what speed? [Front mudguard]",
  "JG": "Front side noise - Can you specify the location? and at what speed? [Front panel noise]",
  "JH": "Front side noise - Can you specify the location? and at what speed? [Wisor noise]",
  "JI": "Front side noise - Can you specify the location? and at what speed? [Headlamp rattling noise]",
  "JJ": "Front side noise - Can you specify the location? and at what speed? [Floor board]",
  "JK": "Front side noise - Can you specify the location? and at what speed? [Lockset noise]",
  "JL": "Front side noise - Can you specify the location? and at what speed? [Petrol cap noise]",
  "JM": "Front side noise - Can you specify the location? and at what speed? [Customer unable to say]",
  "JN": "Front side noise - What kind of road condition?",
  "JO": "Rear side noise-Can you specify the location? and at what speed? [Kicker noise]",
  "JP": "Rear side noise-Can you specify the location? and at what speed? [Rear mudguard]",
  "JQ": "Rear side noise-Can you specify the location? and at what speed? [Accessories noise]",
  "JR": "Rear side noise-Can you specify the location? and at what speed? [Rear panel noise]",
  "JS": "Rear side noise-Can you specify the location? and at what speed? [Seat noise]",
  "JT": "Rear side noise-Can you specify the location? and at what speed? [Muffler noise]",
  "JU": "Rear side noise-Can you specify the location? and at what speed? [gear box]",
  "JV": "Rear side noise-Can you specify the location? and at what speed? [Customer unable to say]",
  "JW": "Rear side noise - What kind of road condition?",
  "JX": "Front side vibration-Can you specify the location? and at what speed? [Wisor Vibration]",
  "JY": "Front side vibration-Can you specify the location? and at what speed? [Foot rest vibration]",
  "JZ": "Front side vibration-Can you specify the location? and at what speed? [Handle bar]",
  "KA": "Front side vibration-Can you specify the location? and at what speed? [Speedometer]",
  "KB": "Front side vibration-Can you specify the location? and at what speed? [Juddering]",
  "KC": "Front side vibration-Can you specify the location? and at what speed? [Seat vibration]",
  "KD": "Front side vibration-Can you specify the location? and at what speed? [Tank vibration]",
  "KE": "Front side vibration - What kind of road condition?",
  "KF": "Rear side vibration - Can you specify the location? and at what speed? [Clutch vibration]",
  "KG": "Rear side vibration - Can you specify the location? and at what speed? [pillion handle vibration]",
  "KH": "Rear side vibration - Can you specify the location? and at what speed? [Muffler vibration]",
  "KI": "Rear side vibration - Can you specify the location? and at what speed? [Saree guard vibration]",
  "KJ": "Rear side vibration - Can you specify the location? and at what speed? [Seat vibration]",
  "KK": "Rear side vibration-What kind of road condition?",
  "KL": "Foot rest vibration-In which side? and at what speed? [LH side]",
  "KM": "Foot rest vibration-In which side? and at what speed? [RH side]",
  "KN": "Foot rest vibration-In which side? and at what speed? [Both side]",
  "KO": "Mirror loose - In which side? and at what speed? [LH side]",
  "KP": "Mirror loose - In which side? and at what speed? [RH side]",
  "KQ": "Mirror loose - In which side? and at what speed? [Both side]",
  "KR": "Mirror small size -Comparing with which competition model?",
  "KS": "Mirror small size - What is customer expectation?",
  "KT": "Front wheel noise-Noise at what speed? and What kind of road condition? [less than 25 kmph]",
  "KU": "Front wheel noise-Noise at what speed? and What kind of road condition? [25-50 kmph]",
  "KV": "Front wheel noise-Noise at what speed? and What kind of road condition? [more than 50 kmph]",
  "KW": "Front wheel wobbling-Wobbling at what speed? and What kind of road condition? [less than 25 kmph]",
  "KX": "Front wheel wobbling-Wobbling at what speed? and What kind of road condition? [25-50 kmph]",
  "KY": "Front wheel wobbling-Wobbling at what speed? and What kind of road condition? [more than 50 kmph]",
  "KZ": "Front wheel wobbling - How frequently you fill air in Tyre?",
  "LA": "Front Tyre skidding- skidding at what speed? and What kind of road condition? [less than 25 kmph]",
  "LB": "Front Tyre skidding- skidding at what speed? and What kind of road condition? [25-50 kmph]",
  "LC": "Front Tyre skidding- skidding at what speed? and What kind of road condition? [more than 50 kmph]",
  "LD": "Front wheel skidding- How frequently you fill air in Tyre?",
  "LE": "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [less than 1000km]",
  "LF": "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [1000-5000km]",
  "LG": "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [5000-10000km]",
  "LH": "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [10000-15000km]",
  "LI": "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [15000-20000km]",
  "LJ": "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [more than 20000 kms]",
  "LK": "Front tyre weak/less life - How frequently you fill air in tyre?",
  "LL": "Front wheel tight",
  "LM": "Front widder tyre required",
  "LN": "Rear wheel noise- Noise at what speed? and What kind of road condition? [less than 25 kmph]",
  "LO": "Rear wheel noise- Noise at what speed? and What kind of road condition? [25-50 kmph]",
  "LP": "Rear wheel noise- Noise at what speed? and What kind of road condition? [more than 50 kmph]",
  "LQ": "Rear wheel wobbling-Wobbling at what speed? and What kind of road condition? [less than 25 kmph]",
  "LR": "Rear wheel wobbling-Wobbling at what speed? and What kind of road condition? [25-50 kmph]",
  "LS": "Rear wheel wobbling-Wobbling at what speed? and What kind of road condition? [more than 50 kmph]",
  "LT": "Rear wheel wobbling - How frequently you fill air in Tyre?",
  "LU": "Rear Tyre skidding- skidding at what speed? and What kind of road condition? [less than 25 kmph]",
  "LV": "Rear Tyre skidding- skidding at what speed? and What kind of road condition? [25-50 kmph]",
  "LW": "Rear Tyre skidding- skidding at what speed? and What kind of road condition? [more than 50 kmph]",
  "LX": "Rear wheel skidding- How frequently you fill air in Tyre?",
  "LY": "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [less than 1000km]",
  "LZ": "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [1000-5000km]",
  "MA": "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [5000-10000km]",
  "MB": "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [10000-15000km]",
  "MC": "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [15000-20000km]",
  "MD": "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [more than 20000 kms]",
  "ME": "Rear tyre weak/less life - How frequently you fill air in tyre?",
  "MF": "Rear wheel tight",
  "MG": "Rear widder tyre required - Comparing with which competition model?",
  "MH": "Battery issues - What is the issue in battery? and Life or frequency of change the Battery? [Battery drain quickly]",
  "MI": "Battery issues - What is the issue in battery? and Life or frequency of change the Battery? [Battery life is less]",
  "MJ": "Battery issues - What is the issue in battery? and Life or frequency of change the Battery? [Battery out of warranty]",
  "MK": "Which brand battery in the vehicle?",
  "ML": "Jerking issues - In what speed vehicle get jerking? and what kind of condition? [Cold condition]",
  "MM": "Jerking issues - In what speed vehicle get jerking? and what kind of condition? [hot condition]",
  "MN": "Jerking issues - If vehicle get Jerking in specific gear?",
  "MO": "If previous is yes means, in which gear the vehicle get Jerking?",
  "MP": "Part not available -Which part not available?",
  "MQ": "Part not available -In which Location it is not available?",
  "MR": "When this Pick-up problem occur, in what speed? [less than 20km]",
  "MS": "When this Pick-up problem occur, in what speed? [20-40km]",
  "MT": "When this Pick-up problem occur, in what speed? [40-60km]",
  "MU": "When this Pick-up problem occur, in what speed? [60-80km]",
  "MV": "When this Pick-up problem occur, in what speed? [more than 80kmph]",
  "MW": "Usually how many passenger will travel?_2",
  "MX": "Usually how much Load are you carry? [less than 50kg]",
  "MY": "Usually how much Load are you carry? [50 - 100kg]",
  "MZ": "Usually how much Load are you carry? [100 - 150kg]",
  "NA": "Usually how much Load are you carry? [150 - 200kg]",
  "NB": "Usually how much Load are you carry? [more than 200kg]",
  "NC": "Running off [Slow speed (less than 30 kmph)]",
  "ND": "Running off [High speed (more than 50 kmph)]",
  "NE": "Running off [During idle condition]",
  "NF": "Running off [While Crossing speed breaker]",
  "NG": "Running off [While De-acceleration]",
  "NH": "Running off [While applying brake]",
  "NI": "Running off [While applying clutch]",
  "NJ": "Throttle / Accelerator issue",
  "NK": "Low ground clearance- If it is using for personal or taxi means, Q-Usually how many passenger will travel? [Rough road]",
  "NL": "Low ground clearance- If it is using for personal or taxi means, Q-Usually how many passenger will travel? [plain road]",
  "NM": "Low ground clearance - [Rough road]",
  "NN": "Low ground clearance - [plain road]",
  "NO": "Stand Problem [Loose]",
  "NP": "Stand Problem [tight]",
  "NQ": "Stand Problem [Returnability]",
  "NR": "Paint issue",
  "NS": "Panel issue [Fitment gap]",
  "NT": "Panel issue [loose fitment]",
  "NU": "Panel issue [Alignment problem]",
  "NV": "Panel issue [damage]",
  "NW": "Panel issue [dent]",
  "NX": "Petrol leakage",
  "NY": "Low fuel tank capacity",
  "NZ": "Low Boot space - Q-What kind of problem?",
  "OA": "Seat issue - Q-What kind of issue?",
  "OB": "Seat issue",
  "OC": "Vehicle Pulling problem - Q-In which side?",
  "OD": "Vehicle Pulling problem - Q-Pulling at what speed?",
  "OE": "Roof top (soft top) issue - Q-What kind of issue?",
  "OF": "Roof top (soft top) issue - Q-Where it is worn-out or tear-off quickly in which location?",
  "OG": "Roof top (soft top) issue - Q-What is the Life or frequency of change the Roof top(soft top)?",
  "OH": "Wiper problem - Q-What kind of problem?",
  "OI": "Wiper problem - Q-What is the Life or frequency of change the Wiper blade?",
  "OJ": "Faster issue - Q-What kind of issue?",
  "OK": "Resolution of Problem is good",
  "OL": "Parts availability & quality",
  "OM": "Skilled Manpower is available in workshop",
  "ON": "Washing Quality (Applicable only for Asia)",
  "OO": "Happy with Service Adviser Behaviour",
  "OP": "Cost & Explanation was good",
  "OQ": "Easy of Payment Method available",
  "OR": "Warranty Policy is good",
  "OS": "Waiting Time was adequate",
  "OT": "Satisfied with Customer Lounge Amenities",
  "OU": "Extension of Operating Hours is very supportive",
  "OV": "Workshop Facilities",
  "OW": "Convenience of Location (Capture Remarks)",
  "OX": "Complaints not resolved",
  "OY": "Parts availability issues Give names of three parts which were not available, with details.",
  "OZ": "Parts availability issues Give names of three parts which were not available, with details._2",
  "PA": "Parts availability issues Give names of three parts which were not available, with details._3",
  "PB": "Improve Skilled Manpower",
  "PC": "Washing Quality (Applicable only for Asia)_2",
  "PD": "Service Adviser Behaviour issues",
  "PE": "Not satisfied with Cost & Explanation",
  "PF": "Easy of Payment Method",
  "PG": "Warranty Policy issues",
  "PH": "Waiting Time is more",
  "PI": "Improve Customer Lounge Amenities",
  "PJ": "Extent the Operating Hours",
  "PK": "Improve Workshop Facilities",
  "PL": "Convenience of Location (Capture Remarks)_2",
  "PM": "C1. Will you recommend / tell / advise your friends, colleague or fellow rider’s for TVS Genuine Spare Parts? (9 & 10 means “you will definitely recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score)",
  "PN": "C1. Will you recommend / tell / advise your friends, colleague or fellow rider’s for TVS Genuine Spare Parts? (9 & 10 means “you will definitely recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [Yes]",
  "PO": "C1. Will you recommend / tell / advise your friends, colleague or fellow rider’s for TVS Genuine Spare Parts? (9 & 10 means “you will definitely recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [May be]",
  "PP": "C1. Will you recommend / tell / advise your friends, colleague or fellow rider’s for TVS Genuine Spare Parts? (9 & 10 means “you will definitely recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [No]",
  "PQ": "C2. How satisfied are you with the availability of TVS Genuine Spare Parts when you need them? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score)",
  "PR": "C2. How satisfied are you with the availability of TVS Genuine Spare Parts when you need them? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [Yes]",
  "PS": "C2. How satisfied are you with the availability of TVS Genuine Spare Parts when you need them? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [May be]",
  "PT": "C2. How satisfied are you with the availability of TVS Genuine Spare Parts when you need them? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [No]",
  "PU": "C3. How satisfied are you with the quality of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score)",
  "PV": "C3. How satisfied are you with the quality of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [Yes]",
  "PW": "C3. How satisfied are you with the quality of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [May be]",
  "PX": "C3. How satisfied are you with the quality of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [No]",
  "PY": "C4. How satisfied are you with the value for money of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score)",
  "PZ": "C4. How satisfied are you with the value for money of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [Yes]",
  "QA": "C4. How satisfied are you with the value for money of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [May be]",
  "QB": "C4. How satisfied are you with the value for money of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick appropriate Score) [Bad]",
  "QC": "1-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
  "QD": "2-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
  "QE": "3-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
  "QF": "4-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
  "QG": "5-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
}

export function getColumnHeader(col: string): string {
  const upper = col.toUpperCase()
  return COLUMN_HEADERS[upper] || `Column ${upper}`
}
