/**
 * Mapping of all 422 Excel column letters (A to PF/OD) to their actual column headers / question names.
 */
export const COLUMN_HEADERS: Record<string, string> = {
  "A": "Timestamp",
  "B": "SURVEY DATE",
  "C": "SURVEYOR NAME",
  "D": "SURVEY LOCATION",
  "E": "BRAND & MODEL  (Qualifying Question)",
  "F": "VIN No. (Qualifying Question)",
  "G": "Please take a picture of the VIN no. and upload it here.  (Qualifying Question)",
  "H": "ODOMETER READING (Kms)",
  "I": "MODE OF PURCHASE",
  "J": "DATE OF PURCHASING THE VEHICLE FROM DEALER / PREVIOUS OWNER",
  "K": "USER NAME",
  "L": "USER AGE (YEARS)",
  "M": "USER AGE GROUP",
  "N": "USER PROFESSION",
  "O": "MOBILE NUMBER",
  "P": "ALTERNATE MOBILE NUMBER",
  "Q": "OWNERSHIP (OWN / HIRED)",
  "R": "FOR WHAT PURPOSE DO YOU USE THE VEHICLE?",
  "S": "MODEL YEAR OF YOUR VEHICLE",
  "T": "HOW LONG HAVE YOU BEEN USING THIS VEHICLE?",
  "U": "PREVIOUS VEHICLE USED Brand & Model",
  "V": "HOW LONG DID YOU USE THE PREVIOUS VEHICLE? (Years)",
  "W": "1. Will you recommend your vehicle to your friends / relatives / family members?",
  "X": "2. On a scale of 0 to 10, how likely are you to recommend your vehicle to your friends and relatives?",
  "Y": "Q2-1. REASON FOR NOT RECOMMENDING [No]",
  "Z": "Q2-2. REASON FOR RECOMMENDING [May be]",
  "AA": "Q2-3. REASON FOR RECOMMENDING [Yes]",
  "AB": "3a)1 why will you recommend your vehicle?",
  "AC": "3a)2 why will you recommend your vehicle?",
  "AD": "3a)3 why will you recommend your vehicle?",
  "AE": "3a)4 why will you recommend your vehicle?",
  "AF": "3a)5 why will you recommend your vehicle?",
  "AG": "3b.1. Areas of dissatisfaction or improvements needed",
  "AH": "3b.2. Areas of dissatisfaction or improvements needed",
  "AI": "3b.3. Areas of dissatisfaction or improvements needed",
  "AJ": "3b.4. Areas of dissatisfaction or improvements needed",
  "AK": "3b.5. Areas of dissatisfaction or improvements needed",
  "AL": "Upload complaint pictures",
  "AM": "Upload complaint pictures 1",
  "AN": "4)1 why will you not recommend your vehicle?",
  "AO": "4)2 why will you not recommend your vehicle?",
  "AP": "4)3 why will you not recommend your vehicle?",
  "AQ": "4)4 why will you not recommend your vehicle?",
  "AR": "4)5 why will you not recommend your vehicle?",
  "AS": "Upload complaint pictures 2",
  "AT": "Upload complaint pictures 3",
  "AU": "Brake",
  "AV": "Electrical",
  "AW": "Engine",
  "AX": "Load",
  "AY": "Maintenance",
  "AZ": "Mileage",
  "BA": "Mirror",
  "BB": "Vehicle",
  "BC": "Seat",
  "BD": "Sound",
  "BE": "Roof top (soft top)",
  "BF": "Spare parts",
  "BG": "Style",
  "BH": "Suspension",
  "BI": "Tyre",
  "BJ": "Vehicle price",
  "BK": "Income",
  "BL": "Windshield",
  "BM": "Brand image",
  "BN": "Q1-1 WHERE DO YOU GET YOUR VEHICLE SERVICED?",
  "BO": "Q1-2 Dealer / Authorized Workshop Name",
  "BP": "Q1-3 WHAT TIME FREQUENCY DO YOU GET YOUR VEHICLE SERVICED?",
  "BQ": "Q1-4 WHAT KMS FREQUENCY DO YOU GET YOUR VEHICLE SERVICED?",
  "BR": "A1. Will you recommend servicing vehicle at Authorized Service workshop / Dealer?",
  "BS": "A2. Service Recommendation rating scale 0-10",
  "BT": "Q2-4. REASON FOR RECOMMENDING [Yes]",
  "BU": "Q2-3. REASON FOR RECOMMENDING [May be]",
  "BV": "Q2-2. REASON FOR RECOMMENDING [No]",
  "BW": "3a)1 Which experience you like the most to recommend Workshop / Dealer?",
  "BX": "3a)2 Which experience you like the most to recommend Workshop / Dealer?",
  "BY": "3a)3 Which experience you like the most to recommend Workshop / Dealer?",
  "BZ": "3b)1 Expectation or areas of improvement in workshop visit for Service",
  "CA": "3b)2 Expectation or areas of improvement in workshop visit for Service",
  "CB": "3b)3 Expectation or areas of improvement in workshop visit for Service",
  "CC": "4)1 Main reasons you have not recommend Workshop / Dealer",
  "CD": "4)2 Main reasons you have not recommend Workshop / Dealer",
  "CE": "4)3 Main reasons you have not recommend Workshop / Dealer",
  "CF": "a) Have you received Service reminder call",
  "CG": "b) Appointment given",
  "CH": "c) Vehicle test drive taken while making job cards",
  "CI": "d) Customer lounge Facilities",
  "CJ": "e) Staff behaviour",
  "CK": "f) All complaints reported are resolved",
  "CL": "g) Fairness of charges",
  "CM": "h) Explanation of Work done",
  "CN": "i) Washing quality",
  "CO": "j) Test drive offered before billing",
  "CP": "A6. Are you satisfied with Vehicle Performance after service? (VPS)",
  "CQ": "A7. Currently are you facing any issues / complaints in vehicle?",
  "CR": "A8. Reported issue to Service advisor during Job card making?",
  "CS": "A9. Fixing problems First Time Right",
  "CT": "A10. Delivery as per promised time",
  "CU": "B1. Reason for not choosing Authorized Service Centers",
  "CV": "B2. Reason for not choosing Authorized Service Centers",
  "CW": "B3. Reason for not choosing Authorized Service Centers",
  "CX": "B2. Quality of Authorized service center (1-10)",
  "CY": "B2. Quality of Authorized service center [Best]",
  "CZ": "B2. Quality of Authorized service center [Bad]",
  "DA": "B2. Quality of Authorized service center [Average]",
  "DB": "Complaint group (L2)",
  "DC": "Complaint group (L2) 2",
  "DD": "Complaint group (L2) 3",
  "DE": "Complaint group (L2) 4",
  "DF": "Complaint group (L2) 5",
  "DG": "Complaint group (L2) 6",
  "DH": "Complaint group (L2) 7",
  "DI": "Complaint group (L2) 8",
  "DJ": "Complaint group (L2) 9",
  "DK": "Complaint group (L2) 10",
  "DL": "Complaint group (L2) 11",
  "DM": "Complaint group (L2) 12",
  "DN": "Complaint group (L2) 13",
  "DO": "Complaint group (L2) 14",
  "DP": "Complaint group (L2) 15",
  "DQ": "Complaint group (L2) 16",
  "DR": "Complaint group (L2) 17",
  "DS": "Complaint group (L2) 18",
  "DT": "Complaint group (L2) 19",
  "DU": "Complaint group (L2) 20",
  "DV": "Complaint group (L2) 21",
  "DW": "Complaint group (L2) 22",
  "DX": "Complaint group (L2) 23",
  "DY": "Complaint group (L2) 24",
  "DZ": "Complaint group (L2) 25",
  "EA": "Complaint group (L2) 26",
  "EB": "Complaint group (L2) 27",
  "EC": "Complaint group (L2) 28",
  "ED": "Complaint group (L2) 29",
  "EE": "Complaint group (L2) 30",
  "EF": "Complaint group (L2) 31",
  "EG": "Complaint group (L2) 32",
  "EH": "Complaint group (L2) 33",
  "EI": "Complaint group (L2) 34",
  "EJ": "Which part not available?",
  "EK": "In which Location it is not available?",
  "EL": "Front brake noise",
  "EM": "Front brake poor",
  "EN": "Front Brake tight",
  "EO": "Rear brake noise",
  "EP": "Rear brake poor",
  "EQ": "Rear brake tight",
  "ER": "ABS Not working",
  "ES": "Hand brake poor",
  "ET": "Brake poor",
  "EU": "Clutch cable [less life]",
  "EV": "Clutch cable [Cable breakage]",
  "EW": "Brake cable [less life]",
  "EX": "Brake cable [Cable breakage]",
  "EY": "Speedo cable [less life]",
  "EZ": "Speedo cable [Cable breakage]",
  "FA": "Chain issues",
  "FB": "Chain case issues",
  "FC": "Clutch loose (Remarks)",
  "FD": "Clutch Noise",
  "FE": "Clutch hard",
  "FF": "Clutch life is low [Clutch plate wear]",
  "FG": "Clutch life is low [Clutch plate burning]",
  "FH": "What is the issue in speedometer?",
  "FI": "TSL (Indicator) [Beeper Sound not coming]",
  "FJ": "TSL (Indicator) [Light Not working]",
  "FK": "TSL (Indicator) [water entry]",
  "FL": "TSL (Indicator) [crack]",
  "FM": "Head light [LED headlamp]",
  "FN": "Tail lamp not working [LED]",
  "FO": "Horn issues",
  "FP": "Switch problem",
  "FQ": "Locks not working [Ignition key not working]",
  "FR": "Locks not working [Side lock not working]",
  "FS": "Locks not working [Fuel tank cap lock not working]",
  "FT": "Engine noise [Top side]",
  "FU": "Engine noise [bottom side]",
  "FV": "Engine noise [Unknown]",
  "FW": "Engine oil leak",
  "FX": "Engine Heat [LH side]",
  "FY": "Engine Heat [RH side]",
  "FZ": "Engine Heat [Both]",
  "GA": "Engine parts rust",
  "GB": "Gear noise Upshifitng",
  "GC": "Gear noise Downshifting",
  "GD": "Gear noise Both",
  "GE": "Gear shifting hard Upshifitng",
  "GF": "Gear shifting hard Downshifting",
  "GG": "Gear shifting hard Both",
  "GH": "Not Coming to Neutral",
  "GI": "Additional gear required",
  "GJ": "Handle bar noise [Cornering]",
  "GK": "Handle bar noise [Pot holes]",
  "GL": "Handle bar noise [Bumpy roads]",
  "GM": "Handle bar noise [Others]",
  "GN": "Handle bar loose [Cornering]",
  "GO": "Handle bar loose [Pot holes]",
  "GP": "Handle bar loose [Bumpy roads]",
  "GQ": "Handle bar loose [Others]",
  "GR": "Handle bar Tight [Cornering]",
  "GS": "Handle bar Tight [Pot holes]",
  "GT": "Handle bar Tight [Bumpy roads]",
  "GU": "Handle bar Tight [Others]",
  "GV": "Handle bar jam [Cornering]",
  "GW": "Handle bar jam [Pot holes]",
  "GX": "Handle bar jam [Bumpy roads]",
  "GY": "Handle bar jam [Others]",
  "GZ": "Handle bar jam [Cornering] 2",
  "HA": "Handle bar jam [Pot holes] 2",
  "HB": "Handle bar jam [Bumpy roads] 2",
  "HC": "Handle bar jam [Others] 2",
  "HD": "handle bar bend [Yes-Is vehicle fall down?]",
  "HE": "handle bar bend [No-Is vehicle fall down?]",
  "HF": "Handle Bar shaking [<=25 kmph]",
  "HG": "Handle Bar shaking [25-50 kmph]",
  "HH": "Handle Bar shaking [>=50 kmph]",
  "HI": "Handle bar vibration [LH side]",
  "HJ": "Handle bar vibration [RH side]",
  "HK": "Handle bar vibration [Both side]",
  "HL": "Kicker issues",
  "HM": "If Kicker is hard",
  "HN": "Q-What mileage are you getting?",
  "HO": "Q-What is your average Speed using regularly?",
  "HP": "Q-What kind of traffic are you mostly using?",
  "HQ": "Usually how many passenger will travel?",
  "HR": "Usually how much Load are you carry?",
  "HS": "Low Speed",
  "HT": "What is the top speed are you Expecting?",
  "HU": "Muffler Noise [Rough road]",
  "HV": "Muffler Noise [plain road]",
  "HW": "Muffler smoke more [Idling speed]",
  "HX": "Muffler smoke more [While running]",
  "HY": "Muffler Rust location",
  "HZ": "Self start problem [Taking Many self for starting]",
  "IA": "Self start problem [in gear condition]",
  "IB": "Self start problem [Not at all starting]",
  "IC": "Kick start problem - What is the issue?",
  "ID": "Front suspension Noise [Cornering]",
  "IE": "Front suspension Noise [Pot holes]",
  "IF": "Front suspension Noise [Bumpy roads]",
  "IG": "Front suspension Noise [Normal road]",
  "IH": "Oil leak from front suspension",
  "II": "Front suspension Hard - Passenger count",
  "IJ": "Front suspension Hard - Load carry",
  "IK": "Front suspension Hard - Air frequency",
  "IL": "Front suspension Soft - Passenger count",
  "IM": "Front suspension Soft - Load carry",
  "IN": "Front suspension Soft - Air frequency",
  "IO": "Rear suspension Hard - Passenger count",
  "IP": "Rear suspension Hard - Load carry",
  "IQ": "Rear suspension Hard - Air frequency",
  "IR": "Rear suspension soft - Passenger count",
  "IS": "Rear suspension soft - Load carry",
  "IT": "Rear suspension soft - Air frequency",
  "IU": "Rear suspension Noise [Cornering]",
  "IV": "Rear suspension Noise [Pot holes]",
  "IW": "Rear suspension Noise [Bumpy roads]",
  "IX": "Rear suspension Noise [Normal road]",
  "IY": "Front side noise [Meter noise]",
  "IZ": "Front side noise [Front mudguard]",
  "JA": "Front side noise [Front panel noise]",
  "JB": "Front side noise [Wisor noise]",
  "JC": "Front side noise [Headlamp rattling noise]",
  "JD": "Front side noise [Floor board]",
  "JE": "Front side noise [Lockset noise]",
  "JF": "Front side noise [Petrol cap noise]",
  "JG": "Front side noise [Customer unable to say]",
  "JH": "Front side noise - Road condition",
  "JI": "Rear side noise [Kicker noise]",
  "JJ": "Rear side noise [Rear mudguard]",
  "JK": "Rear side noise [Accessories noise]",
  "JL": "Rear side noise [Rear panel noise]",
  "JM": "Rear side noise [Seat noise]",
  "JN": "Rear side noise [Muffler noise]",
  "JO": "Rear side noise [gear box]",
  "JP": "Rear side noise [Customer unable to say]",
  "JQ": "Rear side noise - Road condition",
  "JR": "Front side vibration [Wisor Vibration]",
  "JS": "Front side vibration [Foot rest vibration]",
  "JT": "Front side vibration [Handle bar]",
  "JU": "Front side vibration [Speedometer]",
  "JV": "Front side vibration [Juddering]",
  "JW": "Front side vibration [Seat vibration]",
  "JX": "Front side vibration [Tank vibration]",
  "JY": "Front side vibration - Road condition",
  "JZ": "Rear side vibration [Clutch vibration]",
  "KA": "Rear side vibration [pillion handle vibration]",
  "KB": "Rear side vibration [Muffler vibration]",
  "KC": "Rear side vibration [Saree guard vibration]",
  "KD": "Rear side vibration [Seat vibration]",
  "KE": "Rear side vibration - Road condition",
  "KF": "Foot rest vibration [LH side]",
  "KG": "Foot rest vibration [RH side]",
  "KH": "Foot rest vibration [Both side]",
  "KI": "Mirror loose [LH side]",
  "KJ": "Mirror loose [RH side]",
  "KK": "Mirror loose [Both side]",
  "KL": "Mirror small size - Competition model",
  "KM": "Mirror small size - Customer expectation",
  "KN": "Front wheel noise [<=25 kmph]",
  "KO": "Front wheel noise [25-50 kmph]",
  "KP": "Front wheel noise [>50 kmph]",
  "KQ": "Front wheel wobbling [<=25 kmph]",
  "KR": "Front wheel wobbling [25-50 kmph]",
  "KS": "Front wheel wobbling [>50 kmph]",
  "KT": "Front wheel wobbling - Air frequency",
  "KU": "Front Tyre skidding [<=25 kmph]",
  "KV": "Front Tyre skidding [25-50 kmph]",
  "KW": "Front Tyre skidding [>50 kmph]",
  "KX": "Front wheel skidding - Air frequency",
  "KY": "Front tyre weak/less life [<1000km]",
  "KZ": "Front tyre weak/less life [1000-5000km]",
  "LA": "Front tyre weak/less life [5000-10000km]",
  "LB": "Front tyre weak/less life [10000-15000km]",
  "LC": "Front tyre weak/less life [15000-20000km]",
  "LD": "Front tyre weak/less life [>20000 kms]",
  "LE": "Front tyre weak/less life - Air frequency",
  "LF": "Front wheel tight",
  "LG": "Front wider tyre required",
  "LH": "Rear wheel noise [<=25 kmph]",
  "LI": "Rear wheel noise [25-50 kmph]",
  "LJ": "Rear wheel noise [>50 kmph]",
  "LK": "Rear wheel wobbling [<=25 kmph]",
  "LL": "Rear wheel wobbling [25-50 kmph]",
  "LM": "Rear wheel wobbling [>50 kmph]",
  "LN": "Rear wheel wobbling - Air frequency",
  "LO": "Rear Tyre skidding [<=25 kmph]",
  "LP": "Rear Tyre skidding [25-50 kmph]",
  "LQ": "Rear Tyre skidding [>50 kmph]",
  "LR": "Rear wheel skidding - Air frequency",
  "LS": "Rear tyre weak/less life [<1000km]",
  "LT": "Rear tyre weak/less life [1000-5000km]",
  "LU": "Rear tyre weak/less life [5000-10000km]",
  "LV": "Rear tyre weak/less life [10000-15000km]",
  "LW": "Rear tyre weak/less life [15000-20000km]",
  "LX": "Rear tyre weak/less life [>20000 kms]",
  "LY": "Rear tyre weak/less life - Air frequency",
  "LZ": "Rear wheel tight",
  "MA": "Rear wider tyre required - Competition model",
  "MB": "Battery issues [Battery drain quickly]",
  "MC": "Battery issues [Battery life is less]",
  "MD": "Battery issues [Battery out of warranty]",
  "ME": "Which brand battery in the vehicle?",
  "MF": "Jerking issues [Cold condition]",
  "MG": "Jerking issues [Hot condition]",
  "MH": "Jerking issues - Specific gear",
  "MI": "Jerking issues - Which gear?",
  "MJ": "Part not available - Which part?",
  "MK": "Part not available - Location",
  "ML": "Pick-up problem [<20km]",
  "MM": "Pick-up problem [20-40km]",
  "MN": "Pick-up problem [40-60km]",
  "MO": "Pick-up problem [60-80km]",
  "MP": "Pick-up problem [>80kmph]",
  "MQ": "Usually how many passenger will travel? 2",
  "MR": "Usually how much Load are you carry? [<50kg]",
  "MS": "Usually how much Load are you carry? [50-100kg]",
  "MT": "Usually how much Load are you carry? [100-150kg]",
  "MU": "Usually how much Load are you carry? [150-200kg]",
  "MV": "Usually how much Load are you carry? [>200kg]",
  "MW": "Running off [Slow speed (<30 kmph)]",
  "MX": "Running off [High speed (>50 kmph)]",
  "MY": "Running off [During idle condition]",
  "MZ": "Running off [While Crossing speed breaker]",
  "NA": "Running off [While De-acceleration]",
  "NB": "Running off [While applying brake]",
  "NC": "Running off [While applying clutch]",
  "ND": "Throttle / Accelerator issue",
  "NE": "Low ground clearance - Passenger count [Rough road]",
  "NF": "Low ground clearance - Passenger count [Plain road]",
  "NG": "Low ground clearance [Rough road]",
  "NH": "Low ground clearance [Plain road]",
  "NI": "Stand Problem [Loose]",
  "NJ": "Stand Problem [Tight]",
  "NK": "Stand Problem [Returnability]",
  "NL": "Paint issue",
  "NM": "Panel issue [Fitment gap]",
  "NN": "Panel issue [Loose fitment]",
  "NO": "Panel issue [Alignment problem]",
  "NP": "Panel issue [Damage]",
  "NQ": "Panel issue [Dent]",
  "NR": "Petrol leakage",
  "NS": "Low fuel tank capacity",
  "NT": "Low Boot space - Problem type",
  "NU": "Seat issue - Issue type",
  "NV": "Seat issue",
  "NW": "Vehicle Pulling problem - Side",
  "NX": "Vehicle Pulling problem - Speed",
  "NY": "Roof top (soft top) issue - Problem type",
  "NZ": "Roof top (soft top) issue - Worn-out location",
  "OA": "Roof top (soft top) issue - Change frequency",
  "OB": "Wiper problem - Problem type",
  "OC": "Wiper problem - Change frequency",
  "OD": "Fastener issue - Problem type",
  "OE": "Resolution of Problem is good",
  "OF": "Parts availability & quality",
  "OG": "Skilled Manpower is available in workshop",
  "OH": "Washing Quality (Applicable only for Asia)",
  "OI": "Happy with Service Adviser Behaviour",
  "OJ": "Cost & Explanation was good",
  "OK": "Easy of Payment Method available",
  "OL": "Warranty Policy is good",
  "OM": "Waiting Time was adequate",
  "ON": "Satisfied with Customer Lounge Amenities",
  "OO": "Extension of Operating Hours is very supportive",
  "OP": "Workshop Facilities",
  "OQ": "Convenience of Location (Remarks)",
  "OR": "Complaints not resolved",
  "OS": "Parts availability issues (Part 1)",
  "OT": "Parts availability issues (Part 2)",
  "OU": "Parts availability issues (Part 3)",
  "OV": "Improve Skilled Manpower",
  "OW": "Washing Quality (Asia 2)",
  "OX": "Service Adviser Behaviour issues",
  "OY": "Not satisfied with Cost & Explanation",
  "OZ": "Easy of Payment Method",
  "PA": "Warranty Policy issues",
  "PB": "Waiting Time is more",
  "PC": "Improve Customer Lounge Amenities",
  "PD": "Extend Operating Hours",
  "PE": "Improve Workshop Facilities",
  "PF": "Convenience of Location (Remarks 2)"
}

export function getColumnHeader(col: string): string {
  const upper = col.toUpperCase()
  return COLUMN_HEADERS[upper] || `Column ${upper}`
}
