export const UPLOAD_TEMPLATE_HEADERS: string[] = [
  "Timestamp",
  "SURVEY DATE",
  "SURVEYOR NAME",
  "SURVEY LOCATION",
  "BRAND & MODEL (Qualifying Question)",
  "VIN No. (Qualifying Question)",
  "Please take a picture of the VIN no. and upload it here. (Qualifying Question)",
  "ODOMETER READING (Kms)",
  "MODE OF PURCHASE",
  "DATE OF PURCHASING THE VEHICLE FROM DEALER / PREVIOUS OWNER",
  "USER NAME",
  "USER AGE (YEARS) (enter only a full number between 18 to 60)",
  "USER AGE GROUP",
  "USER PROFESSION",
  "MOBILE NUMBER",
  "ALTERNATE MOBILE NUMBER",
  "OWNERSHIP (OWN / HIRED)",
  "FOR WHAT PURPOSE DO YOU USE THE VEHICLE?",
  "MODEL YEAR OF YOUR VEHICLE",
  "HOW LONG HAVE YOU BEEN USING THIS VEHICLE?",
  "PREVIOUS VEHICLE USED\r\nBrand & Model",
  "HOW LONG DID YOU USE THE PREVIOUS VEHICLE? (Years)",
  "1. Will you recommend your vehicle to your friends / relatives / family members?",
  "2. On a scale of 0 to 10, how likely are you to recommend your vehicle to your friends and relatives? (9 & 10 means “Yes Always recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”)",
  "Q2-1. REASON FOR NOT RECOMMENDING [If answer to the above question Q4-1 is \"No\", select a rating from 0 (will not at all recommend) to 6 (recommend but with reservations)] below: [No]",
  "Q2-2. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"May be\", select a rating 7 (less likely) or 8 (more likely)] below: [May be]",
  "Q2-3. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"Yes\", select a rating 9 (Will recommend) or 10 (definitely/gladly recommend)] below: [Yes]",
  "3a)1 why will you recommend your vehicle?",
  "3a)2 why will you recommend your vehicle?",
  "3a)3 why will you recommend your vehicle?",
  "3a)4 why will you recommend your vehicle?",
  "3a)5 why will you recommend your vehicle?",
  "3b.1. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "3b. 2. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "3b. 3. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "3b. 4. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "3b. 5. Can you please tell us if there are any areas of dissatisfaction or improvements needed?",
  "Upload complaint pictures",
  "Upload complaint pictures 1",
  "4)1 why will you not recommend your vehicle?",
  "4)2 why will you not recommend your vehicle?",
  "4)3 why will you not recommend your vehicle?",
  "4)4 why will you not recommend your vehicle?",
  "4)5 why will you not recommend your vehicle?",
  "Upload complaint pictures2",
  "Upload complaint pictures3",
  "Brake",
  "Electrical",
  "Engine",
  "Load",
  "Maintenance",
  "Mileage",
  "Mirror",
  "Vehicle",
  "Seat",
  "Sound",
  "Roof top (soft top)",
  "Spare parts",
  "Style",
  "Suspension",
  "Tyre",
  "Vehicle price",
  "Income",
  "Windshield",
  "Brand image",
  "Q1-1 WHERE DO YOU GET YOUR VEHICLE SERVICED?",
  "Q1-2 Dealer / Authorized Workshop Name",
  "Q1-3 WHAT TIME FREQUENCY DO YOU GET YOUR VEHICLE SERVICED?",
  "Q1-4 WHAT KMS FREQUENCY DO YOU GET YOUR VEHICLE SERVICED?",
  "A1. Will you recommend / tell / advise your friends or family members for servicing their vehicle at Authorized Service workshop / Authorized Dealer?",
  "A2. We have a rating scale from 0 to 10 to understand this better. (9 & 10 means “you will definitely recommend workshop / Dealers to service their vehicle”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choose",
  "Q2-4. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"Yes\", select a rating from 9 (will recommend) to 10 (definitely/gladly recommend)] below: [Yes]",
  "Q2-3. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"May be\", select a rating from 7 (less likely recommend) to 8 (more likely recommend)] below: [May be]",
  "Q2-2. REASON FOR RECOMMENDING [If answer to the above question Q4-1 is \"No\", select a rating from 0 (will not at all recommend) to 6 (recommend but with reservations)] below: [No]",
  "3a)1 Which experience you like the most to recommend Workshop / Dealer?",
  "3a)2 Which experience you like the most to recommend Workshop / Dealer?",
  "3a)3 Which experience you like the most to recommend Workshop / Dealer?",
  "3b)1 Can you please tell us if there are any expectation or areas of improvement you wish to experience in your workshop visit for Service?",
  "3b)2 Can you please tell us if there are any expectation or areas of improvement you wish to experience in your workshop visit for Service?",
  "3b)3 Can you please tell us if there are any expectation or areas of improvement you wish to experience in your workshop visit for Service?",
  "4)1 What are the main reasons for you have not recommend Workshop / Dealer?",
  "4)2 What are the main reasons for you have not recommend Workshop / Dealer?",
  "4)3 What are the main reasons for you have not recommend Workshop / Dealer?",
  "a) Have you received Service reminder call",
  "b) Appointment given",
  "c) Vehicle test drive taken while making job cards to understand the complaints",
  "d) Customer lounge Facilities",
  "e) Staff behaviour",
  "f) All complaints reported are resolved",
  "g) Fairness of charges",
  "h) Explanation of Work done",
  "i) Washing quality",
  "j) Test drive offered before billing",
  "A6. Are you satisfied with Vehicle Performance after service? (VPS)",
  "A7. Currently are you facing any issues / complaints in vehicle? \r\nNo of customer not satisfied with vehicle performance after service",
  "A8. Have you reported this issue to the Service advisor during Job card making during your last Visit?",
  "A9. Fixing problems First Time Right",
  "A10. Delivery as per promised time",
  "A11. Overall, how satisfied are you with your experience at our workshop/dealership for servicing your vehicle? (Please rate your satisfaction on a scale of “0 to 10”)",
  "A11. Overall, how satisfied are you with your experience at our workshop/dealership for servicing your vehicle? (Please rate your satisfaction on a scale of “0 to 10”)4",
  "A11. Overall, how satisfied are you with your experience at our workshop/dealership for servicing your vehicle? (Please rate your satisfaction on a scale of “0 to 10”)5",
  "A11. Overall, how satisfied are you with your experience at our workshop/dealership for servicing your vehicle? (Please rate your satisfaction on a scale of “0 to 10”)6",
  "B1. Reason for not choosing the Authorized Service Centers?",
  "B2. Reason for not choosing the Authorized Service Centers?",
  "B3. Reason for not choosing the Authorized Service Centers?",
  "B2. How would you rate the quality of Authorized service center? (Choose any score from 1 - 10, \"1 means worst, 10 means best\")",
  "B2. How would you rate the quality of Authorized service center? (Choose any score from 9,10 means best\") [Best]",
  "B2. How would you rate the quality of Authorized service center? (Choose any score from1 to 6 means Bad\") [Bad]",
  "B2. How would you rate the quality of Authorized service center? (Choose any score from 7,8 means average\") [Average]",
  "Complaint group (L2)",
  "Complaint group (L2)7",
  "Complaint group (L2)8",
  "Complaint group (L2)9",
  "Complaint group (L2)10",
  "Complaint group (L2)11",
  "Complaint group (L2)12",
  "Complaint group (L2)13",
  "Complaint group (L2)14",
  "Complaint group (L2)15",
  "Complaint group (L2)16",
  "Complaint group (L2)17",
  "Complaint group (L2)18",
  "Complaint group (L2)19",
  "Complaint group (L2)20",
  "Complaint group (L2)21",
  "Complaint group (L2)22",
  "Complaint group (L2)23",
  "Complaint group (L2)24",
  "Complaint group (L2)25",
  "Complaint group (L2)26",
  "Complaint group (L2)27",
  "Complaint group (L2)28",
  "Complaint group (L2)29",
  "Complaint group (L2)30",
  "Complaint group (L2)31",
  "Complaint group (L2)32",
  "Complaint group (L2)33",
  "Complaint group (L2)34",
  "Complaint group (L2)35",
  "Complaint group (L2)36",
  "Complaint group (L2)37",
  "Complaint group (L2)38",
  "Complaint group (L2)39",
  "Which part not available?",
  "In which Location it is not available?",
  "Front brake noise",
  "Front brake poor",
  "Front Brake tight",
  "Rear brake noise",
  "Rear brake poor",
  "Rear brake tight",
  "ABS Not working",
  "Hand brake poor",
  "Brake poor",
  "Clutch cable [less life]",
  "Clutch cable [Cable breakage]",
  "Brake cable [less life]",
  "Brake cable [Cable breakage]",
  "Speedo cable [less life]",
  "Speedo cable [Cable breakage]",
  "Chain issues",
  "Chain case issues",
  "Clutch loose (Remarks)",
  "Clutch Noise",
  "Clutch hard",
  "Clutch life is low [Clutch plate wear]",
  "Clutch life is low [Clutch plate burning]",
  "What is the issue in speedometer?",
  "TSL (Indicator) [Beeper Sound not coming]",
  "TSL (Indicator) [Light Not working]",
  "TSL (Indicator) [water entry]",
  "TSL (Indicator) [crack]",
  "Head light [DC headlamp]",
  "Head light [LED headlamp]",
  "Tail lamp not working [Bulb]",
  "Tail lamp not working [LED]",
  "Horn issues",
  "Switch problem",
  "Locks not working [Ignition key not working]",
  "Locks not working [Side lock not working]",
  "Locks not working [Fuel tank cap lock not working]",
  "Engine noise [Top side]",
  "Engine noise [bottom side]",
  "Engine noise [Unknown]",
  "Engine oil leak",
  "Engine Heat [LH side]",
  "Engine Heat [RH side]",
  "Engine Heat [Both]",
  "Engine parts rust",
  "Gear noise Upshifitng",
  "Gear noise Downshifting",
  "Gear noise Both",
  "Gear shifting hard Upshifitng",
  "Gear shifting hard Downshifting",
  "Gear shifting hard Both",
  "Not Coming to Neutral",
  "Additional gear required",
  "Handle bar noise [Cornering]",
  "Handle bar noise [Pot holes]",
  "Handle bar noise [Bumpy roads]",
  "Handle bar noise [Others]",
  "Handle bar loose [Cornering]",
  "Handle bar loose [Pot holes]",
  "Handle bar loose [Bumpy roads]",
  "Handle bar loose [Others]",
  "Handle bar Tight [Cornering]",
  "Handle bar Tight [Pot holes]",
  "Handle bar Tight [Bumpy roads]",
  "Handle bar Tight [Others]",
  "Handle bar jam [Cornering]",
  "Handle bar jam [Pot holes]",
  "Handle bar jam [Bumpy roads]",
  "Handle bar jam [Others]",
  "Handle bar jam [Cornering]40",
  "Handle bar jam [Pot holes]41",
  "Handle bar jam [Bumpy roads]42",
  "Handle bar jam [Others]43",
  "handle bar bend [Yes-Is vehicle fall down?]",
  "handle bar bend [No-Is vehicle fall down?]",
  "Handle Bar shaking [<=25 kmph]",
  "Handle Bar shaking [25-50 kmph]",
  "Handle Bar shaking [>=50 kmph]",
  "Handle bar vibration [LH side]",
  "Handle bar vibration [RH side]",
  "Handle bar vibration [Both side]",
  "Kicker issues",
  "If Kicker is hard",
  "Q-What mileage are you getting?",
  "Q-What is your average Speed using regularly?",
  "Q-What kind of traffic are you mostly using?",
  "Usually how many passenger will travel?",
  "Usually how much Load are you carry?",
  "Low Speed",
  "What is the top speed are you Expecting?",
  "Muffler Noise [Rough road]",
  "Muffler Noise [plain road]",
  "Muffler smoke more [Idling speed]",
  "Muffler smoke more [While running]",
  "Muffler Rust-Where is the rust and specify the location?",
  "Self start problem - What is the issue? [Taking Many self for starting]",
  "Self start problem - What is the issue? [in gear condition]",
  "Self start problem - What is the issue? [Not at all starting]",
  "Kick start problem - What is the issue?",
  "Front suspension Noise Issue [Cornering]",
  "Front suspension Noise Issue [Pot holes]",
  "Front suspension Noise Issue [Bumpy roads]",
  "Front suspension Noise Issue [Normal road]",
  "Oil leak from front suspension",
  "Front suspension Hard - Usually how many passenger will travel?",
  "Front suspension Hard - Usually how much Load are you carry?",
  "Front suspension Hard - How frequently you fill air in Tyre?",
  "Front suspension Soft - Usually how many passenger will travel?",
  "Front suspension Soft-Usually how much Load are you carry?",
  "Front suspension Soft - How frequently you fill air in Tyre?",
  "Rear suspension Hard - Usually how many passenger will travel?",
  "Rear suspension Hard - Usually how much Load are you carry?",
  "Rear suspension Hard-How frequently you fill air in Tyre?",
  "Rear suspension soft- Usually how many passenger will travel?",
  "Rear suspension soft - Usually how much Load are you carry?",
  "Rear suspension soft -How frequently you fill air in Tyre?",
  "Rear suspension Noise - When it is happening? and at what speed? [Cornering]",
  "Rear suspension Noise - When it is happening? and at what speed? [Pot holes]",
  "Rear suspension Noise - When it is happening? and at what speed? [Bumpy roads]",
  "Rear suspension Noise - When it is happening? and at what speed? [Normal road]",
  "Front side noise - Can you specify the location? and at what speed? [Meter noise]",
  "Front side noise - Can you specify the location? and at what speed? [Front mudguard]",
  "Front side noise - Can you specify the location? and at what speed? [Front panel noise]",
  "Front side noise - Can you specify the location? and at what speed? [Wisor noise]",
  "Front side noise - Can you specify the location? and at what speed? [Headlamp rattling noise]",
  "Front side noise - Can you specify the location? and at what speed? [Floor board]",
  "Front side noise - Can you specify the location? and at what speed? [Lockset noise]",
  "Front side noise - Can you specify the location? and at what speed? [Petrol cap noise]",
  "Front side noise - Can you specify the location? and at what speed? [Customer unable to say]",
  "Front side noise - What kind of road condition?",
  "Rear side noise-Can you specify the location? and at what speed? [Kicker noise]",
  "Rear side noise-Can you specify the location? and at what speed? [Rear mudguard]",
  "Rear side noise-Can you specify the location? and at what speed? [Accessories noise]",
  "Rear side noise-Can you specify the location? and at what speed? [Rear panel noise]",
  "Rear side noise-Can you specify the location? and at what speed? [Seat noise]",
  "Rear side noise-Can you specify the location? and at what speed? [Muffler noise]",
  "Rear side noise-Can you specify the location? and at what speed? [gear box]",
  "Rear side noise-Can you specify the location? and at what speed? [Customer unable to say]",
  "Rear side noise - What kind of road condition?",
  "Front side vibration-Can you specify the location? and at what speed? [Wisor Vibration]",
  "Front side vibration-Can you specify the location? and at what speed? [Foot rest vibration]",
  "Front side vibration-Can you specify the location? and at what speed? [Handle bar]",
  "Front side vibration-Can you specify the location? and at what speed? [Speedometer]",
  "Front side vibration-Can you specify the location? and at what speed? [Juddering]",
  "Front side vibration-Can you specify the location? and at what speed? [Seat vibration]",
  "Front side vibration-Can you specify the location? and at what speed? [Tank vibration]",
  "Front side vibration - What kind of road condition?",
  "Rear side vibration - Can you specify the location? and at what speed? [Clutch vibration]",
  "Rear side vibration - Can you specify the location? and at what speed? [pillion handle vibration]",
  "Rear side vibration - Can you specify the location? and at what speed? [Muffler vibration]",
  "Rear side vibration - Can you specify the location? and at what speed? [Saree guard vibration]",
  "Rear side vibration - Can you specify the location? and at what speed? [Seat vibration]",
  "Rear side vibration-What kind of road condition?",
  "Foot rest vibration-In which side? and at what speed? [LH side]",
  "Foot rest vibration-In which side? and at what speed? [RH side]",
  "Foot rest vibration-In which side? and at what speed? [Both side]",
  "Mirror loose - In which side? and at what speed? [LH side]",
  "Mirror loose - In which side? and at what speed? [RH side]",
  "Mirror loose - In which side? and at what speed? [Both side]",
  "Mirror small size -Comparing with which competition model?",
  "Mirror small size - What is customer expectation?",
  "Front wheel noise-Noise at what speed? and What kind of road condition? [less than 25 kmph]",
  "Front wheel noise-Noise at what speed? and What kind of road condition? [25-50 kmph]",
  "Front wheel noise-Noise at what speed? and What kind of road condition? [more than 50 kmph]",
  "Front wheel wobbling-Wobbling at what speed? and What kind of road condition? [less than 25 kmph]",
  "Front wheel wobbling-Wobbling at what speed? and What kind of road condition? [25-50 kmph]",
  "Front wheel wobbling-Wobbling at what speed? and What kind of road condition? [more than 50 kmph]",
  "Front wheel wobbling - How frequently you fill air in Tyre?",
  "Front Tyre skidding- skidding at what speed? and What kind of road condition? [less than 25 kmph]",
  "Front Tyre skidding- skidding at what speed? and What kind of road condition? [25-50 kmph]",
  "Front Tyre skidding- skidding at what speed? and What kind of road condition? [more than 50 kmph]",
  "Front wheel skidding- How frequently you fill air in Tyre?",
  "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [less than 1000km]",
  "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [1000-5000km]",
  "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [5000-10000km]",
  "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [10000-15000km]",
  "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [15000-20000km]",
  "Front tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [more than 20000 kms]",
  "Front tyre weak/less life - How frequently you fill air in tyre?",
  "Front wheel tight",
  "Front widder tyre required",
  "Rear wheel noise- Noise at what speed? and What kind of road condition? [less than 25 kmph]",
  "Rear wheel noise- Noise at what speed? and What kind of road condition? [25-50 kmph]",
  "Rear wheel noise- Noise at what speed? and What kind of road condition? [more than 50 kmph]",
  "Rear wheel wobbling-Wobbling at what speed? and What kind of road condition? [less than 25 kmph]",
  "Rear wheel wobbling-Wobbling at what speed? and What kind of road condition? [25-50 kmph]",
  "Rear wheel wobbling-Wobbling at what speed? and What kind of road condition? [more than 50 kmph]",
  "Rear wheel wobbling - How frequently you fill air in Tyre?",
  "Rear Tyre skidding- skidding at what speed? and What kind of road condition? [less than 25 kmph]",
  "Rear Tyre skidding- skidding at what speed? and What kind of road condition? [25-50 kmph]",
  "Rear Tyre skidding- skidding at what speed? and What kind of road condition? [more than 50 kmph]",
  "Rear wheel skidding- How frequently you fill air in Tyre?",
  "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [less than 1000km]",
  "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [1000-5000km]",
  "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [5000-10000km]",
  "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [10000-15000km]",
  "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [15000-20000km]",
  "Rear tyre weak/less life - What is the Life or frequency of change the tyre? and What kind of road condition? [more than 20000 kms]",
  "Rear tyre weak/less life - How frequently you fill air in tyre?",
  "Rear wheel tight",
  "Rear widder tyre required - Comparing with which competition model?",
  "Battery issues - What is the issue in battery? and Life or frequency of change the Battery? [Battery drain quickly]",
  "Battery issues - What is the issue in battery? and Life or frequency of change the Battery? [Battery life is less]",
  "Battery issues - What is the issue in battery? and Life or frequency of change the Battery? [Battery out of warranty]",
  "Which brand battery in the vehicle?",
  "Jerking issues - In what speed vehicle get jerking? and what kind of condition? [Cold condition]",
  "Jerking issues - In what speed vehicle get jerking? and what kind of condition? [hot condition]",
  "Jerking issues - If vehicle get Jerking in specific gear?",
  "If previous is yes means, in which gear the vehicle get Jerking?",
  "Part not available -Which part not available?",
  "Part not available -In which Location it is not available?",
  "When this Pick-up problem occur, in what speed? [less than 20km]",
  "When this Pick-up problem occur, in what speed? [20-40km]",
  "When this Pick-up problem occur, in what speed? [40-60km]",
  "When this Pick-up problem occur, in what speed? [60-80km]",
  "When this Pick-up problem occur, in what speed? [more than 80kmph]",
  "Usually how many passenger will travel?44",
  "Usually how much Load are you carry? [less than 50kg]",
  "Usually how much Load are you carry? [50 - 100kg]",
  "Usually how much Load are you carry? [100 - 150kg]",
  "Usually how much Load are you carry? [150 - 200kg]",
  "Usually how much Load are you carry? [more than 200kg]",
  "Running off [Slow speed (less than 30 kmph)]",
  "Running off [High speed (more than 50 kmph)]",
  "Running off [During idle condition]",
  "Running off [While Crossing speed breaker]",
  "Running off [While De-acceleration]",
  "Running off [While applying brake]",
  "Running off [While applying clutch]",
  "Throttle / Accelerator issue",
  "Low ground clearance- \r\nIf it is using for personal or taxi means, Q-Usually how many passenger will travel? [Rough road]",
  "Low ground clearance- \r\nIf it is using for personal or taxi means, Q-Usually how many passenger will travel? [plain road]",
  "Low ground clearance - [Rough road]",
  "Low ground clearance - [plain road]",
  "Stand Problem [Loose]",
  "Stand Problem [tight]",
  "Stand Problem [Returnability]",
  "Paint issue",
  "Panel issue [Fitment gap]",
  "Panel issue [loose fitment]",
  "Panel issue [Alignment problem]",
  "Panel issue [damage]",
  "Panel issue [dent]",
  "Petrol leakage",
  "Low fuel tank capacity",
  "Low Boot space - Q-What kind of problem?",
  "Seat issue - Q-What kind of issue?",
  "Seat issue",
  "Vehicle Pulling problem - Q-In which side?",
  "Vehicle Pulling problem - Q-Pulling at what speed?",
  "Roof top (soft top) issue - Q-What kind of issue?",
  "Roof top (soft top) issue - Q-Where it is worn-out or tear-off quickly in which location?",
  "Roof top (soft top) issue - Q-What is the Life or frequency of change the Roof top(soft top)?",
  "Wiper problem - Q-What kind of problem?",
  "Wiper problem - Q-What is the Life or frequency of change the Wiper blade?",
  "Faster issue - Q-What kind of issue?",
  "Resolution of Problem is good",
  "Parts availability & quality",
  "Skilled Manpower is available in workshop",
  "Washing Quality\r\n(Applicable only for Asia)",
  "Happy with Service Adviser Behaviour",
  "Cost & Explanation was good",
  "Easy of Payment Method available",
  "Warranty Policy is good",
  "Waiting Time was adequate",
  "Satisfied with Customer Lounge Amenities",
  "Extension of Operating Hours is very supportive",
  "Workshop Facilities",
  "Convenience of Location\r\n(Capture Remarks)",
  "Complaints not resolved",
  "Parts availability issues \r\nGive names of three parts which were not available, with details.",
  "Parts availability issues\r\nGive names of three parts which were not available, with details.",
  "Parts availability issues\r\nGive names of three parts which were not available, with details.45",
  "Improve Skilled Manpower",
  "Washing Quality\r\n(Applicable only for Asia)46",
  "Service Adviser Behaviour issues",
  "Not satisfied with Cost & Explanation",
  "Easy of Payment Method",
  "Warranty Policy issues",
  "Waiting Time is more",
  "Improve Customer Lounge Amenities",
  "Extent the Operating Hours",
  "Improve Workshop Facilities",
  "Convenience of Location\r\n(Capture Remarks)47",
  "C1. Will you recommend / tell / advise your friends, colleague or fellow rider’s for TVS Genuine Spare Parts? (9 & 10 means “you will definitely recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choose a",
  "C1. Will you recommend / tell / advise your friends, colleague or fellow rider’s for TVS Genuine Spare Parts? (9 & 10 means “you will definitely recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choos48",
  "C1. Will you recommend / tell / advise your friends, colleague or fellow rider’s for TVS Genuine Spare Parts? (9 & 10 means “you will definitely recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choos49",
  "C1. Will you recommend / tell / advise your friends, colleague or fellow rider’s for TVS Genuine Spare Parts? (9 & 10 means “you will definitely recommend”, 7 & 8 means “May be recommend”, 6 and below means “No, definitely not recommend”) You can choos50",
  "C2. How satisfied are you with the availability of TVS Genuine Spare Parts when you need them? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would",
  "C2. How satisfied are you with the availability of TVS Genuine Spare Parts when you need them? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score wo51",
  "C2. How satisfied are you with the availability of TVS Genuine Spare Parts when you need them? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score wo52",
  "C2. How satisfied are you with the availability of TVS Genuine Spare Parts when you need them? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score wo53",
  "C3. How satisfied are you with the quality of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (Tick",
  "C3. How satisfied are you with the quality of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (T54",
  "C3. How satisfied are you with the quality of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (T55",
  "C3. How satisfied are you with the quality of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to give? (T56",
  "C4. How satisfied are you with the value for money of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to giv",
  "C4. How satisfied are you with the value for money of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to 57",
  "C4. How satisfied are you with the value for money of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to 58",
  "C4. How satisfied are you with the value for money of TVS Genuine Spare Parts? (9 & 10 means “Extremely Satisfied”, 7 & 8 means “Satisfied”, 6 and below means “Not Satisfied”) You can choose any score between 0 and 10. So which score would you like to 59",
  "1-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
  "2-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
  "3-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
  "4-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
  "5-C5. What is the primary reason for the above rating (in “Ques: C1”) you given for TVS Genuine Spare Parts?",
  "",
  "",
  "",
  "",
  "",
  "",
];
